// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxfrfekvpaooakzpbzmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4ZnJmZWt2cGFvb2FrenBiem1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1Mzc0MjksImV4cCI6MjA2MjExMzQyOX0.CfEIUZZAVtimsRBR8dZTEl3AU7LdHNAfO8QDcM7s9To";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);